ci: check for mlnx-ofed updates in evergreen

diff --git a/.github/workflows/evergreen.yml b/.github/workflows/evergreen.yml
--- a/.github/workflows/evergreen.yml
+++ b/.github/workflows/evergreen.yml
@@ -29,9 +29,10 @@ jobs:
       - name: Push changes
         id: push
         run: |
+          git config user.name github-actions[bot]
+          git config user.email github-actions[bot]@users.noreply.github.com
+
           if [[ `git status flake.lock --porcelain` ]]; then
-            git config user.name github-actions[bot]
-            git config user.email github-actions[bot]@users.noreply.github.com
             git add flake.lock
             git commit -m "bot: nix flake update"
             git push
@@ -50,3 +51,27 @@ jobs:
               repo: context.repo.repo,
               event_type: 'build',
             });
+      - name: Check for newer mlnx-ofed version
+        id: run_update_script
+        run: |
+          if nix run .#updater -- --commit; then
+            commits_count=$(git rev-list --all --count)
+            if [ "$commits_count" -ge 2 ]; then
+              echo "pr_title=$(git show -s --format=%s HEAD)" >> $GITHUB_OUTPUT
+            fi
+          else
+            echo "updater execution failed"
+            exit 1
+          fi
+      - name: Create pull request
+        uses: peter-evans/create-pull-request@v7
+        if: steps.run_update_script.outputs.pr_title != ''
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
+          branch: "bot/bump-mlnx-ofed-src"
+          title: ${{ steps.run_update_script.outputs.pr_title }}
+          delete-branch: true
+          body: "This pull request is created automatically by the evergreen action which runs periodically to bump packages."
+          labels: "bot"
+          reviewers: "codgician"
